---
- name: Provision AWS Infrastructure
  hosts: localhost
  become: false
  gather_facts: false

  vars_files:
    - vars/create_infra.yml
    - vars/create_dc.yml
    - vars/create_nodes.yml
    - vars/secrets.yml

  tasks:
    - name: Create infrastructure (network)
      ansible.builtin.include_tasks:
        file: tasks/create_infra.yml

    - name: Provision domain controller
      ansible.builtin.include_tasks:
        file: tasks/create_ec2.yml
      vars:
        add_to_inventory: true
        add_to_groups: [domain_controllers]
        config: "{{ dc_config }}"

    - name: Record domain controller ip
      ansible.builtin.set_stats:
        data:
          win_domain_controller: "{{ dc_config.instance_name }}"
          win_domain_controller_ip: "{{ r_ec2.instances[0].private_ip_address }}"

    - name: Provision additional nodes
      loop: "{{ nodes }}"
      loop_control:
        loop_var: config
        label: "{{ config.instance_name }}"
      ansible.builtin.include_tasks:
        file: tasks/create_ec2.yml
      vars:
        add_to_inventory: true
        add_to_groups: [domain_computers]
        win_domain_controller: "{{ dc_config.instance_name }}"
