---
- name: Join Domain
  hosts: role_domain_computers 
  become: false
  gather_facts: false

  vars:
    ansible_user: ec2-user
    ansible_password: "{{ ec2_admin_password }}"
    ansible_winrm_transport: credssp

  vars_files:
    - vars/domain_join.yml
    - vars/secrets.yml

  tasks:
    - name: Join new windows hosts to domain 
      ansible.builtin.include_tasks:
        file: tasks/domain_join.yml
