---
- name: Provision AWS Infrastructure
  hosts: localhost
  become: false
  gather_facts: false

  vars_files:
    - vars/create_infra.yml
    - vars/create_dc.yml
    - vars/create_nodes.yml
    - vars/secrets_ec2.yml

  tasks:
    - name: Create infrastructure (network)
      ansible.builtin.include_tasks:
        file: tasks/create_infra.yml

    - name: Provision domain controller
      ansible.builtin.include_tasks:
        file: tasks/create_ec2.yml
      vars:
        config: "{{ dc_config }}"

    - name: Record domain controller ip
      ansible.builtin.set_fact:
        win_domain_controller_ip: "{{ r_ec2.instances[0].private_ip_address }}"

    - name: Provision additional nodes
      loop: "{{ nodes }}"
      loop_control:
        loop_var: config
        label: "{{ config.instance_name }}"
      ansible.builtin.include_tasks:
        file: tasks/create_ec2.yml
      vars:
        add_to_inventory: true
        add_to_groups: [domain_ou_computers]

- name: Configure Domain Controller
  hosts: dc01.autodotes.com
  become: false
  gather_facts: false

  vars_files:
    - vars/config_domain.yml
    - vars/secrets_domain.yml

  tasks:
    - name: Configure domain controller
      ansible.builtin.include_tasks:
        file: tasks/config_domain.yml

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks:
        file: handlers/config_domain.yml

- name: Join Domain
  hosts: domain_ou_computers
  become: false
  gather_facts: false

  vars_files:
    - vars/join_domain.yml
    - vars/secrets_domain.yml

  tasks:
    - name: Join new windows hosts to domain
      ansible.builtin.include_tasks:
        file: tasks/join_domain.yml
