---
- hosts: all
  gather_facts: yes

  tasks:
    - name: Report Ansible Facts
      debug:
        var: ansible_facts

    - name: Patch server
      include_role: 
        name: patch

    # - name: Patch server (turn off reporting)
    #   include_role: patch
    #   vars:
    #     patch_failed_report: false

    # - name: Patch server (specific patch)
    #   include_role: patch
    #   vars:
    #     patch_categories:
    #       - SecurityUpdates
    #     patch_kbs:
    #       - KB4056892
    #       - KB4073117