---
- name: Test
  hosts: controlbox
  gather_facts: false

  tasks:
    - name: include proxmox_kvm_decomm role
      ansible.builtin.include_role:
        name: proxmox_kvm_decomm
      vars:
        proxmox_kvm_decomm_name: hcl-guest-1