---
- name: Decommission a Proxmox Windows VM
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: true

  tasks:
    - name: Add comment | init decomm
      ansible.builtin.include_tasks:
        file: tasks/snow_comment.yml
      vars:
        snow_comment: "Beginning decomm process for {{ inventory_hostname }}"

    - name: Add comment | interface facts
      ansible.builtin.include_tasks:
        file: tasks/snow_comment.yml
      vars:
        snow_comment: "[code]<h4>Network Interface Facts</h4>[/code]{{ hostvars[inventory_hostname]['ansible_interfaces'] | to_nice_json | codify }}"  

    - name: Describe instance | smb shares
      register: r_smb_shares
      ansible.windows.win_powershell:
        script: Get-SmbShare | ConvertTo-Json
        
    - name: Add comment | smb shares
      ansible.builtin.include_tasks:
        file: tasks/snow_comment.yml
      vars:
        snow_comment: "[code]<h4>SMB Share Facts</h4>[/code]{{ r_smb_shares.output[0] | from_json | to_nice_json | codify }}"    

    - name: Describe instance | SQL Server
      register: r_sql_server
      ansible.windows.win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL

    - name: Add comment | sql server
      when: r_sql_server.exists
      ansible.builtin.include_tasks:
        file: tasks/snow_comment.yml
      vars:
        snow_comment: "[code]<h4>SQL Facts</h4>[/code]{{ r_sql_server.properties | to_nice_json | codify }}"   

    - name: Add comment | sql server
      when: not r_sql_server.exists
      ansible.builtin.include_tasks:
        file: tasks/snow_comment.yml
      vars:
        snow_comment: "SQL Server not installed on this machine"
