---
- name: Decommission a Proxmox Windows VM
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: true

  tasks:
    - name: Add note | init decomm
      delegate_to: localhost
      servicenow.itsm.api:
        resource: sc_req_item
        sys_id: "{{ sys_id }}"
        action: patch
        data:
          comments: "Beginning decomm process for {{ inventory_hostname }}"

    - name: Add note | interface facts
      delegate_to: localhost
      servicenow.itsm.api:
        resource: sc_req_item
        sys_id: "{{ sys_id }}"
        action: patch
        data:
          comments: "{{ hostvars[inventory_hostname]['ansible_interfaces'] | to_nice_json | codify }}"    
