---
- name: Decommission a Proxmox Windows VM
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: true

  tasks:
    - name: Add comment | init decomm
      delegate_to: localhost
      servicenow.itsm.api:
        resource: sc_req_item
        sys_id: "{{ sys_id }}"
        action: patch
        data:
          comments: "Beginning decomm process for {{ inventory_hostname }}"

    - name: Add comment | interface facts
      delegate_to: localhost
      servicenow.itsm.api:
        resource: sc_req_item
        sys_id: "{{ sys_id }}"
        action: patch
        data:
          comments: "{{ hostvars[inventory_hostname]['ansible_interfaces'] | to_nice_json | codify }}"    

    - name: Describe instance | smb shares
      register: r_smb_shares
      ansible.windows.win_powershell:
        script: Get-SmbShare | ConvertTo-Json
        
    - name: Add comment | smb shares
      delegate_to: localhost
      servicenow.itsm.api:
        resource: sc_req_item
        sys_id: "{{ sys_id }}"
        action: patch
        data:
          comments: "{{ r_smb_shares.output[0] | from_json | to_nice_json | codify }}"    