---
- name: Decommission a Proxmox Windows VM
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: true

  tasks:
    - name: Add comment | init decomm
      ansible.builtin.include_tasks:
        file: tasks/snow_comment.yml
      vars:
        snow_comment: "Beginning decomm process for {{ inventory_hostname }}"

    - name: Add comment | interface facts
      ansible.builtin.include_tasks:
        file: tasks/snow_comment.yml
      vars:
        snow_comment: "<h3>Network Interface Facts</h3>{{ hostvars[inventory_hostname]['ansible_interfaces'] | to_nice_json | codify }}"  

    - name: Describe instance | smb shares
      register: r_smb_shares
      ansible.windows.win_powershell:
        script: Get-SmbShare | ConvertTo-Json
        
    - name: Add comment | smb shares
      ansible.builtin.include_tasks:
        file: tasks/snow_comment.yml
      vars:
        snow_comment: "<h3>SMB Share Facts</h3>{{ r_smb_shares.output[0] | from_json | to_nice_json | codify }}"    

    - name: Describe instance | SQL Server
      ansible.windows.win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL
      register: current_version