---
- name: Decommission a Proxmox Windows VM
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: false

  tasks:
    - name: Print ServiceNow information
      ansible.builtin.debug:
        msg: |
          Message: {{ _msg }}
          RITM: {{ ritm }}
          Category Item: {{ cat_item }}
          Requested For: {{ requested_for }}

    - name: Get requested item
      register: r_req_item
      servicenow.itsm.api_info:
        resource: sc_req_item
        sys_id: "{{ sys_id }}"

    - name: Print results
      debug:
        var: r_req_item
