---
- name: Create Proxmox VMs
  hosts: controlbox
  connection: local

  tasks:
    - name: Assert required proxmox creds
      ansible.builtin.assert:
        that:
          - proxmox_api_host is defined
          - proxmox_api_user is defined
          - proxmox_api_token_id is defined
          - proxmox_api_token_secret is defined
        fail_msg: "Missing one of the required proxmox authentication variables - promox_api_[host|user|token_id|token_secret]"

    - name: Build VMs via defined configs
      when: proxmox_ve_configs is defined
      loop: "{{ proxmox_ve_configs }}"
      loop_control:
        loop_var: pve_config
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_api_host }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        api_user: "{{ proxmox_api_user }}"
        acpi: "{{ pve_config.acpi | default(omit) }}"
        agent: "{{ pve_config.agent | default(omit) }}"
        archive: "{{ pve_config.archive | default(omit) }}"
        args: "{{ pve_config.args | default(omit) }}"
        autostart: "{{ pve_config.autostart | default(omit) }}"
        balloon: "{{ pve_config.balloon | default(omit) }}"
        bios: "{{ pve_config.bios | default(omit) }}"
        boot: "{{ pve_config.boot | default(omit) }}"
        clone: "{{ pve_config.clone }}"
        cores: "{{ pve_config.cores | default(omit) }}"
        cpu: "{{ pve_config.cpu | default(omit) }}"
        cpulimit: "{{ pve_config.cpulimit | default(omit) }}"
        cpuunits: "{{ pve_config.cpuunits | default(omit) }}"
        delete: "{{ pve_config.delete | default(omit) }}"
        description: "{{ pve_config.description | default(omit) }}"
        digest: "{{ pve_config.digest | default(omit) }}"
        efidisk0: "{{ pve_config.efidisk0 | default(omit) }}"
        force: "{{ pve_config.force | default(omit) }}"
        format: "{{ pve_config.format | default(omit) }}"
        freeze: "{{ pve_config.freeze | default(omit) }}"
        full: "{{ pve_config.full | default(omit) }}"
        hostpci: "{{ pve_config.hostpci | default(omit) }}"
        hotplug: "{{ pve_config.hotplug | default(omit) }}"
        hugepages: "{{ pve_config.hugepages | default(omit) }}"
        ide: "{{ pve_config.ide | default(omit) }}"
        ipconfig: "{{ pve_config.ipconfig | default(omit) }}"
        keyboard: "{{ pve_config.keyboard | default(omit) }}"
        kvm: "{{ pve_config.kvm | default(omit) }}"
        localtime: "{{ pve_config.localtime | default(omit) }}"
        lock: "{{ pve_config.lock | default(omit) }}"
        machine: "{{ pve_config.machine | default(omit) }}"
        memory: "{{ pve_config.memory | default(omit) }}"
        migrate_downtime: "{{ pve_config.migrate_downtime | default(omit) }}"
        migrate_speed: "{{ pve_config.migrate_speed | default(omit) }}"
        name: "{{ pve_config.name }}"
        nameservers: "{{ pve_config.nameservers | default(omit) }}"
        net: "{{ pve_config.net }}"
        newid: "{{ pve_config.newid }}"
        node: "{{ pve_config.node }}"
        numa_enabled: "{{ pve_config.numa_enabled }}"
        numa: "{{ pve_config.numa }}"
        onboot: "{{ pve_config.onboot }}"
        ostype: "{{ pve_config.ostype }}"
        parallel: "{{ pve_config.parallel }}"
        pool: "{{ pve_config.pool }}"
        protection: "{{ pve_config.protection }}"
        proxmox_default_behavior: "{{ pve_config.proxmox_default_behavior }}"
        reboot: "{{ pve_config.reboot }}"
        revert: "{{ pve_config.revert }}"
        sata: "{{ pve_config.sata }}"
        scsi: "{{ pve_config.scsi }}"
        scsihw: "{{ pve_config.scsihw }}"
        searchdomains: "{{ pve_config.searchdomains }}"
        serial: "{{ pve_config.serial }}"
        shares: "{{ pve_config.shares }}"
        skiplock: "{{ pve_config.skiplock }}"
        smbios: "{{ pve_config.smbios }}"
        snapname: "{{ pve_config.snapname }}"
        sockets: "{{ pve_config.sockets | default(omit) }}"
        sshkeys: "{{ pve_config.sshkeys }}"
        startdate: "{{ pve_config.startdate }}"
        startup: "{{ pve_config.startup }}"
        state: present
        storage: "{{ pve_config.storage }}"
        tablet: "{{ pve_config.tablet }}"
        tags: "{{ pve_config.tags }}"
        target: "{{ pve_config.target }}"
        tdf: "{{ pve_config.tdf }}"
        template: "{{ pve_config.template }}"
        timeout: "{{ pve_config.timeout | default(1200) }}"
        update: "{{ pve_config.update }}"
        validate_certs: "{{ pve_config.validate_certs }}"
        vcpus: "{{ pve_config.vcpus }}"
        vga: "{{ pve_config.vga }}"
        virtio: "{{ pve_config.virtio }}"
        vmid: "{{ pve_config.vmid }}"
        watchdog: "{{ pve_config.watchdog }}"

    - name: Build VMs from survey
      when: use_pve_survey | default(false)
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_api_host }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        api_user: "{{ proxmox_api_user }}"
        acpi: "{{ pve_survey_acpi | default(omit) }}"
        agent: "{{ pve_survey_agent | default(omit) }}"
        archive: "{{ pve_survey_archive | default(omit) }}"
        args: "{{ pve_survey_args | default(omit) }}"
        autostart: "{{ pve_survey_autostart | default(omit) }}"
        balloon: "{{ pve_survey_balloon | default(omit) }}"
        bios: "{{ pve_survey_bios | default(omit) }}"
        boot: "{{ pve_survey_boot | default(omit) }}"
        clone: "{{ pve_survey_clone }}"
        cores: "{{ pve_survey_cores | default(omit) }}"
        cpu: "{{ pve_survey_cpu | default(omit) }}"
        cpulimit: "{{ pve_survey_cpulimit | default(omit) }}"
        cpuunits: "{{ pve_survey_cpuunits | default(omit) }}"
        delete: "{{ pve_survey_delete | default(omit) }}"
        description: "{{ pve_survey_description | default(omit) }}"
        digest: "{{ pve_survey_digest | default(omit) }}"
        efidisk0: "{{ pve_survey_efidisk0 | default(omit) }}"
        force: "{{ pve_survey_force | default(omit) }}"
        format: "{{ pve_survey_format | default(omit) }}"
        freeze: "{{ pve_survey_freeze | default(omit) }}"
        full: "{{ pve_survey_full | default(omit) }}"
        hostpci: "{{ pve_survey_hostpci | default(omit) }}"
        hotplug: "{{ pve_survey_hotplug | default(omit) }}"
        hugepages: "{{ pve_survey_hugepages | default(omit) }}"
        ide: "{{ pve_survey_ide | default(omit) }}"
        ipconfig: "{{ pve_survey_ipconfig | default(omit) }}"
        keyboard: "{{ pve_survey_keyboard | default(omit) }}"
        kvm: "{{ pve_survey_kvm | default(omit) }}"
        localtime: "{{ pve_survey_localtime | default(omit) }}"
        lock: "{{ pve_survey_lock | default(omit) }}"
        machine: "{{ pve_survey_machine | default(omit) }}"
        memory: "{{ pve_survey_memory | default(omit) }}"
        migrate_downtime: "{{ pve_survey_migrate_downtime | default(omit) }}"
        migrate_speed: "{{ pve_survey_migrate_speed | default(omit) }}"
        name: "{{ pve_survey_name }}"
        nameservers: "{{ pve_survey_nameservers | default(omit) }}"
        net: "{{ pve_survey_net }}"
        newid: "{{ pve_survey_newid }}"
        node: "{{ pve_survey_node }}"
        numa_enabled: "{{ pve_survey_numa_enabled }}"
        numa: "{{ pve_survey_numa }}"
        onboot: "{{ pve_survey_onboot }}"
        ostype: "{{ pve_survey_ostype }}"
        parallel: "{{ pve_survey_parallel }}"
        pool: "{{ pve_survey_pool }}"
        protection: "{{ pve_survey_protection }}"
        proxmox_default_behavior: "{{ pve_survey_proxmox_default_behavior }}"
        reboot: "{{ pve_survey_reboot }}"
        revert: "{{ pve_survey_revert }}"
        sata: "{{ pve_survey_sata }}"
        scsi: "{{ pve_survey_scsi }}"
        scsihw: "{{ pve_survey_scsihw }}"
        searchdomains: "{{ pve_survey_searchdomains }}"
        serial: "{{ pve_survey_serial }}"
        shares: "{{ pve_survey_shares }}"
        skiplock: "{{ pve_survey_skiplock }}"
        smbios: "{{ pve_survey_smbios }}"
        snapname: "{{ pve_survey_snapname }}"
        sockets: "{{ pve_survey_sockets | default(omit) }}"
        sshkeys: "{{ pve_survey_sshkeys }}"
        startdate: "{{ pve_survey_startdate }}"
        startup: "{{ pve_survey_startup }}"
        state: present
        storage: "{{ pve_survey_storage }}"
        tablet: "{{ pve_survey_tablet }}"
        tags: "{{ pve_survey_tags }}"
        target: "{{ pve_survey_target }}"
        tdf: "{{ pve_survey_tdf }}"
        template: "{{ pve_survey_template }}"
        timeout: "{{ pve_survey_timeout | default(1200) }}"
        update: "{{ pve_survey_update }}"
        validate_certs: "{{ pve_survey_validate_certs }}"
        vcpus: "{{ pve_survey_vcpus }}"
        vga: "{{ pve_survey_vga }}"
        virtio: "{{ pve_survey_virtio }}"
        vmid: "{{ pve_survey_vmid }}"
        watchdog: "{{ pve_survey_watchdog }}"
