---
- hosts: all
  gather_facts: true
 
  tasks:
  # - debug:
  #     msg: "{{ vault_ansible_password }}"
  #     var: ansible_facts 

  - name: get powershell version linux
    shell: |
      $ver = $PSVersionTable
      return $PSVersionTable.PSVersion.Major
    args:
      executable: /usr/bin/pwsh
    register: ps_major_version
    delegate_to: localhost
    
  - name: print powershell version
    debug:
      var: ps_major_version.stdout  