---
- name: Ping windows server
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: false

  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Report Ansible Facts
      ansible.builtin.debug:
        var: ansible_facts