---
- name: Ping windows server
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: true

  tasks:
    - name: Join Autodotes domain
      when: join_domain | default(false)
      block:
        - name: Configure name servers
          ansible.builtin.win_shell: |
            Set-DnsClientServerAddress -InterfaceIndex 6 -ServerAddresses ("{{ hostvars['dc01.AUTODOTES.LOCAL']['ansible_host'] }}","192.168.0.1")

        - name: Join autodotes.local domain
          register: r_domain_membership
          throttle: 1
          ansible.windows.win_domain_membership:
            dns_domain_name: "{{ win_domain }}"
            hostname: "{{ inventory_hostname.split('.')[0] }}"
            domain_admin_user: "{{ win_domain_admin }}@{{ win_domain }}"
            domain_admin_password: "{{ win_domain_admin_password }}"
            domain_ou_path: "OU=Computers,OU=lab,DC=autodotes,DC=local"
            state: domain

        - name: Remove host vars to use windows group vars
          ansible.controller.host:
            name: "{{ inventory_hostname }}"
            inventory: "Proxmox Inventory"
            state: present
            variables: 
              domain_name: "{{ win_domain }}"
              domain_dns_address: "{{ hostvars['dc01.AUTODOTES.LOCAL']['ansible_host'] }}"
              domain_ou_path: "OU=Computers,OU=lab,DC=autodotes,DC=local"