---
- name: Ping windows server
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: true

  tasks:
    - name: Print facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts[inventory_hostname] }}"